# Generated by Django 2.1.5 on 2019-02-23 02:28

import costcomp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsoler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('guaranteed', models.IntegerField()),
                ('level', models.CharField(choices=[('GC', 'Grauate Coach'), ('FAO', 'Former Admissions Officer')], default='GC', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packStart', models.DateField(default=datetime.date.today)),
                ('packEnd', models.DateField(default=costcomp.models.enddate_default)),
                ('faoStart', models.DateField(blank=True, default=datetime.date.today)),
                ('faoEnd', models.DateField(blank=True, default=costcomp.models.enddate_default)),
                ('gcStart', models.DateField(blank=True, default=datetime.date.today)),
                ('gcEnd', models.DateField(blank=True, default=costcomp.models.enddate_default)),
                ('counsolers', models.ManyToManyField(related_name='enrollments', to='costcomp.Counsoler')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('gcHours', models.IntegerField(verbose_name='GC hours')),
                ('faoHours', models.IntegerField(verbose_name='FAO hours')),
                ('courseHours', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='costcomp.Package'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='students',
            field=models.ManyToManyField(related_name='enrollments', to='costcomp.Student'),
        ),
    ]
