# Generated by Django 2.1.5 on 2019-02-14 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsoler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('guaranteed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startMonth', models.DateTimeField(default=datetime.date.today)),
                ('endMonth', models.DateTimeField(default=datetime.date.today)),
                ('counsolers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='costcomp.Counsoler')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('counsolers', models.ManyToManyField(through='costcomp.Enrollment', to='costcomp.Counsoler')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='costcomp.Package'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='costcomp.Student'),
        ),
    ]
