# Generated by Django 2.1.5 on 2019-02-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcomp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='counsolers',
            new_name='counsoler',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='endMonth',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='startMonth',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='students',
            new_name='student',
        ),
    ]
