# Generated by Django 2.1.5 on 2019-02-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='var',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
